const reportSource = {
  reportID: '2288427556088185',
  reportName: '#admins',
  type: 'chat',
  chatType: 'policyAdmins',
  ownerEmail: '__fake__',
  ownerAccountID: 0,
  managerEmail: '__fake__',
  managerID: 0,
  policyID: 'D861A57D1BA2FC93',
  participantAccountIDs: [15221359],
  isPinned: true,
  lastReadTime: '2023-10-03 11:31:13.171',
  lastReadSequenceNumber: 0,
  lastVisibleActionCreated: '2023-10-03 11:31:13.171',
  lastVisibleActionLastModified: '2023-10-03 11:31:13.171',
  lastMessageText: '',
  lastActorAccountID: 0,
  notificationPreference: 'always',
  welcomeMessage: '',
  stateNum: 0,
  statusNum: 0,
  oldPolicyName: '',
  isOwnPolicyExpenseChat: false,
  lastMessageHtml: '',
  hasOutstandingIOU: false,
  writeCapability: 'all',
  total: 0,
  currency: 'USD',
  submitterPayPalMeAddress: '',
  isWaitingOnBankAccount: false,
  hasDraft: false,
  pendingFields: {
    createChat: null,
  },
  errorFields: {
    createChat: null,
  },
  isOptimisticReport: false,
};
export default reportSource;
